# Generated by Django 4.1.1 on 2022-12-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('count', models.FloatField(verbose_name='Значение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.category', verbose_name='Категори')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['created_at'],
            },
        ),
    ]
