# Generated by Django 4.1.4 on 2022-12-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_report_alter_image_options_alter_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['date_month']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='date_month',
        ),
    ]
