# Generated by Django 4.1.4 on 2022-12-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_alter_report_date_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_month',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
