# Generated by Django 4.1.4 on 2022-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0011_report_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report/%Y/%m/%d/', verbose_name='Report file'),
        ),
    ]
