# Generated by Django 4.1.4 on 2022-12-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0014_alter_category_slug_alter_report_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Picture'),
        ),
    ]
