# Generated by Django 4.1.4 on 2022-12-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0015_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='expend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
